version: '3'
services:
  mongodb:
    container_name: MongoDB
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./tmp/data/db:/data/db

  node:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: Node-Server
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - 3000:3000
    depends_on:
      - mongodb
    environment:
      - JWT_SECRET=YourOwnKey
      - JWT_EXPIRES_IN=2h
      - DB_CONNECTION_STRING=mongodb://mongodb:27017/CTStore
    tty: true
    stdin_open: true
    
  redis:
    image: redis:latest
    container_name: Redis
    restart: always
    ports:
      - 6379:6379

volumes:
  mongodb: {}